services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    platform: linux/amd64   # 👈 Add this line
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: litlaunch
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"